version: "3.1"


services:
  db:
    image: postgres
    volumes:
      - ./data_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=user
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=haha@123
    ports:
    - "5433:5433"
      
  boilerpalte:
    build: .
    container_name: drf_bolierplate
    tty: true
    command: > 
      bash -c "python manage.py makemigrations
      && python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
