# Generated by Django 4.2.4 on 2023-09-04 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_forgetpassword_is_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('super_admin', 'Super Admin')], default='user', max_length=255),
        ),
        migrations.AlterField(
            model_name='forgetpassword',
            name='reset_email_token',
            field=models.CharField(max_length=255),
        ),
    ]
